---
- name: install PHP_CodeSniffer
  git: >
    repo=https://github.com/squizlabs/PHP_CodeSniffer.git
    dest=/usr/local/lib/phpcs

- name: symlink phpcs into the bin
  file: >
    src=/usr/local/lib/phpcs/scripts/phpcs dest=/usr/local/bin/phpcs
    state=link

- name: symlink phpcbf into the PATH
  file: >
    src=/usr/local/lib/phpcs/scripts/phpcbf dest=/usr/local/bin/phpcbf
    state=link

- name: install WordPress-Coding-Standards (wpcs)
  git: >
    repo=https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
    dest=/usr/local/lib/wpcs

- name: tell PHP_CodeSniffer to use wpcs
  shell: phpcs --config-set installed_paths /usr/local/lib/wpcs

- name: create an alias for wpcs
  lineinfile: >
    dest=/home/vagrant/.bashrc
    insertafter=EOF
    line='alias wpcs="phpcs --standard=WordPress"'

- name: create an alias for wpcbf
  lineinfile: >
    dest=/home/vagrant/.bashrc
    insertafter=EOF
    line='alias wpcbf="phpcbf --standard=WordPress"'
