---
- name: install xdebug
  apt: >
    pkg=php5-xdebug state=latest install_recommends=no

- name: install the settings script for xdebug
  template: >
    src=xdebug.ini.j2 dest=/etc/php5/mods-available/xdebug.ini
    owner=root group=root mode=0644
  notify: restart php5-fpm

- name: create the log directory
  shell: "mkdir -p /vagrant/log/xdebug/"

- name: set the vagrant user as the owner
  shell: "chown -R vagrant:vagrant /vagrant/log/"

- name: create the xdebug log
  file: >
    path=/vagrant/log/xdebug/xdebug.log state=touch
    owner=vagrant group=vagrant mode=0777
